channels:
- conda-forge
dependencies:
- python=3.13.1
- pip<=24.3.1
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - jinja2==3.1.5
  - lightning==2.4.0
  - matplotlib==3.8.2
  - numpy==1.26.4
  - pandas==2.2.3
  - rich==13.9.4
  - scipy==1.15.1
  - torch-geometric==2.6.1
  - torch==2.5.1
name: mlflow-env
